[package]
name = "jtime"
version = "0.1.1"
edition = "2021"


[dependencies]
anyhow = "1.0.96"
chrono = "0.4"
clap = { version = "4.5.31", features = ["derive"] }
cli-table = "0.4.9"
colored = "3.0.0"
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


[dev-dependencies]
tempfile = "3.6"

[profile.release]
strip = true
opt-level = "z"  # Optimize for size over speed
lto = true       # Enable Link Time Optimization
codegen-units = 1  # Reduce parallel code generation for better optimization
panic = "abort"  # Removes panic unwinding code
